name: research_navigation
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin: ^0.6.2
  google_fonts:

  cupertino_icons: ^1.0.2
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.9
  url_launcher: ^6.1.5
  geolocator: ^7.6.2
  geocoding: ^2.0.5
  http:
  uuid: ^3.0.5
  flutter_geocoder: ^0.2.2-nullsafety
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/Arrow_01/
